### ISSUE TITLE
Setting up firehose takes at least 10 seconds

### ISSUE THREAD

**Issue by angeljruiz** [dendro-naap/dendro-cli#32]
Currently, we're waiting 10 seconds before setting up firehose to ensure all policies have been attached to our IAM role

We should poll AWS to see if the policies have been attached instead of just waiting

**Comment by petertdelia** [comment]
We've fixed this. But now we have to check that the policies are attached when the role has already been created.

**Comment by angeljruiz** [comment]
closed with #41
