### ISSUE TITLE
deploying multiple times breaks connections

### ISSUE THREAD

**Issue by petertdelia** [dendro-naap/dendro-cli#56]
If we deploy twice, a new bucket is created but firehose points to the old bucket. 

Also, the new bucket isn't updated with the old lambda's information, so the lambda trigger is broken.

Haven't tested timestream, but we think it should work.

**Comment by AndiLavera** [comment]
@angeljruiz The only thing that gets duplicated is the s3 bucket. Why not list the s3 buckets prior to making one. If you find one with `dendro-s3-bucket-`, then don't deploy a new one? That would fix that issue. Nothing else gets duplicated or changed. The only other thing would be to make more timestream tables if need be. 

Ex:
First deploy makes a `postgres-log` table. Then i reconfigure to add `host-metrics` and redeploy. That should make a new timestream table for host-metrics right?
