### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by AndiLavera** [dendro-naap/dendro-cli#6]
This is for @angeljruiz 

I know the script your wrote is only a test file for now but i do believe it will slowly become the script file we will execute to deploy user pipelines. With that said, I think we should think of error handling & promise rejection now.

I suggest every aws function that returns a promise should both `resolve` & `reject` based on whatever aws returns. If each aws action can `reject` when aws fails then we can use the `try/catch` syntax paired with `async/await` which i believe we both agree is more readable

It would turn:

```js
 const [bucketErr, bucketData] = await AWSWrapper.createBucket(NEW_BUCKET_NAME)
  if (bucketErr) {
    console.error(bucketErr)
  } else {
    console.log('success')
  }
```

into something like:

```js
try {
  GlobalState.bucketData = await AWSWrapper.createBucket(NEW_BUCKET_NAME)
} catch (e) {
  console.error(e)
  // Handle error here
}
```

Let me know what you think!

**Comment by angeljruiz** [comment]
closed w #14
