### ISSUE TITLE
Timestream data retention

### ISSUE THREAD

**Issue by AndiLavera** [dendro-naap/dendro-cli#61]
Each timestream table is set to store data 30 days in memory & 30 days on disk. This should be changed to 7 days for memory & something like 2-5 years for magnetic? @nlicalzi What are you thoughts?

**Comment by nlicalzi** [comment]
Yeah I think 7 days in memory is good, and we can make that the limit/timespan for our custom dashboards so we're not doing slow queries to populate those

**Comment by AndiLavera** [comment]
Cool. What do you think the magnet retention rate should be?

**Comment by nlicalzi** [comment]
Good question, we should do some estimating and costing for that. I'd say a year, so you can look at yearly performance since promotions and raises are on a yearly cycle and if you're hitting your SLAs you'll want to bring that up 😛
