### ISSUE TITLE
RFC: Rename commands

### ISSUE THREAD

**Issue by AndiLavera** [dendro-naap/dendro-cli#89]
Right now the command are pretty random. `deploy` & `configure` are ambiguous. Deploy what? Configure what?

I suggest we namespace each command similar to how `start:server` is. My suggestion is the the following:

```sh
aws:deploy
aws:list
aws:teardown

vector:configure
vector:review

server:start

clean
help
```

**Comment by nlicalzi** [comment]
I think we should go with:

```
deploy
list-services
teardown

configure
review

start-dashboard

clean
help
```
